FROM ubuntu:20.04

LABEL maintainer="Alessandro Verlato <alessandro@fancypixel.it>"

ARG DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-l", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates gawk autoconf automake bison libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev sqlite3 libgmp-dev libreadline-dev libssl-dev \
    build-essential wget curl dnsutils vim libev4 libevent-dev make gcc g++ git patch libpq-dev libicu-dev zlib1g-dev gnupg2 procps
RUN apt-get clean && rm -rf /var/lib/apt/lists/* && truncate -s 0 /var/log/*log

RUN echo "alias ll='ls $LS_OPTIONS -lha'" >> /root/.bashrc

# Install RVM
RUN gpg2 --recv-keys --keyserver keyserver.ubuntu.com 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
RUN curl -sSL https://get.rvm.io | bash -s stable
RUN echo "source /etc/profile.d/rvm.sh" | tee -a /root/.bashrc


# Non cambiare le istruzioni qui sopra se non STRETTAMENTE NECESSARIO

# *** Install Ruby ***

#RUN rvm install $ruby_version

## Fetch download URL for this version and download archive
#RUN wget $(wget -q -O - "https://cache.ruby-lang.org/pub/ruby/index.txt" | grep -oP "(http.+${ruby_version}.tar.gz)")
## Extract archive
#RUN tar -xvzf $ruby_version.tar.gz
## Set workdir to extracted archive
#WORKDIR /$ruby_version
## Configure
#RUN ./configure --prefix=/compiled_$ruby_version --enable-load-relative --disable-install-doc
#RUN make
#RUN make install
