FROM ubuntu_18_04_rvm:latest

LABEL maintainer="Alessandro Verlato <alessandro@fancypixel.it>"

ARG ruby_version=ruby-3.0.1

SHELL ["/bin/bash", "-l", "-c"]
# Check if ruby_version starts with "ruby-"
RUN if [[ $ruby_version != ruby-* ]]; then echo "\n\nError: ruby_version argument must start with 'ruby-'\n\n" && exit -1;fi
RUN source /etc/profile.d/rvm.sh
# Non cambiare le istruzioni qui sopra se non STRETTAMENTE NECESSARIO

# *** Install Ruby ***
#
RUN rvm install $ruby_version
WORKDIR /running
RUN apt-get update && apt-get install -y network-manager
